

test_dijkstra:  main.c utilities.c graph.c pqueue.c total_order.c dijkstra.c dijkstra.h utilities.h graph.h pqueue.h total_order.h node.h
	gcc main.c utilities.c graph.c pqueue.c total_order.c dijkstra.c -L. -l:libbinheap.so -o test_dijkstra 